
version: "3.7"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cat/health?h=st || exit 1"]
      interval: 50s
      timeout: 30s
      retries: 5
    environment:
      - cluster.name=fdj-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
  db:
    container_name: db
    image: mongo # container image to be used
    restart: always
    ports: # expose ports in “host:container” format
      - 27017:27017
    environment: #env variables to pass into the container
      MONGODB_DATABASE: fdj-football-league


#Docker Networks
networks:
  fdj-network:
