FROM node:12-alpine

# Install PM2
RUN npm install -g pm2

RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		g++ \
		gcc \
		git \
		make \
		python \
	;

# Set working directory
RUN mkdir -p /var/www/fdj
WORKDIR /var/www/fdj

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /var/www/fdj/api/node_modules/.bin:$PATH
# create user with no password
RUN adduser --disabled-password demo

# Copy existing application directory contents
COPY . /var/www/fdj
# install and cache app dependencies
COPY package.json /var/www/fdj/api/package.json
COPY package-lock.json /var/www/fdj/api/package-lock.json

# grant a permission to the application
RUN chown -R demo:demo /var/www/fdj
USER demo

# clear application caching
RUN npm cache clean --force
# install all dependencies
RUN npm install

EXPOSE 3000
# start run in production environment
#CMD [ "npm", "run", "pm2:delete" ]
#CMD [ "npm", "run", "build-docker:dev" ]

# start run in development environment
CMD [ "npm", "run", "start" ]
